# Schema for configuration files of the multiselect module.

multiselect.settings:
  type: config_object
  label: 'Multiselect settings'
  mapping:
    multiselect:
      type: mapping
      label: 'Multiselect'
      mapping:
        widths:
          type: integer
          label: 'Width of Select Boxes (in pixels)'
