action.configuration.opigno_module_add_activity:
  type: action_configuration_default
  label: 'Add activity to Module'

opigno_module.settings:
  type: 'config_object'
  label: 'Module settings'
  mapping:
    description:
      type: string
    availability_closed_message:
      type: text
    availability_unavailable_message:
      type: text

opigno_module.settings:
  type: 'config_object'
  label: 'Module settings'
  mapping:
    description:
      type: string
    availability_closed_message:
      type: text
    availability_unavailable_message:
      type: text