name: Configuration Rewrite
type: module
description: Rewrites existing configuration on module installation via using a "rewrite" folder in the config directory.
core: 8.x
php: 7.1
core_version_requirement: ^8 || ^9
package: Configuration

# Information added by Drupal.org packaging script on 2020-05-22
version: '8.x-1.3'
project: 'config_rewrite'
datestamp: 1590160271
