config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
  - field.storage.group.field_learning_path_description
  - search_api.server.default_server
  - core.entity_view_mode.group.teaser_of_group
  - core.entity_view_mode.node.search_index
  module:
  - user
  - search_api
  - group
  - node
id: default_index
name: 'Default content index'
description: 'Default content index created by the Database Search Defaults module'
read_only: false
field_settings:
  author:
    label: 'Author name'
    datasource_id: 'entity:node'
    property_path: 'uid:entity:name'
    type: string
    dependencies:
      module:
      - user
  changed:
    label: Changed
    datasource_id: 'entity:node'
    property_path: changed
    type: date
  created:
    label: 'Authored on'
    datasource_id: 'entity:node'
    property_path: created
    type: date
  field_learning_path_description:
    label: Description
    datasource_id: 'entity:group'
    property_path: field_learning_path_description
    type: text
    dependencies:
      config:
      - field.storage.group.field_learning_path_description
  label:
    label: Title
    datasource_id: 'entity:group'
    property_path: label
    type: string
  node_grants:
    label: 'Node access information'
    property_path: search_api_node_grants
    type: string
    indexed_locked: true
    type_locked: true
    hidden: true
  rendered_item:
    label: 'Rendered item'
    property_path: rendered_item
    type: text
    configuration:
      roles:
        anonymous: anonymous
      view_mode:
        'entity:group':
          learning_path: teaser_of_group
        'entity:node':
          article: search_index
          forum: search_index
          page: search_index
  status:
    label: 'Publishing status'
    datasource_id: 'entity:node'
    property_path: status
    type: boolean
    indexed_locked: true
    type_locked: true
  sticky:
    label: 'Sticky at top of lists'
    datasource_id: 'entity:node'
    property_path: sticky
    type: boolean
  title:
    label: Title
    datasource_id: 'entity:node'
    property_path: title
    type: text
    boost: !!float 8
  type:
    label: 'Content type'
    datasource_id: 'entity:node'
    property_path: type
    type: string
  uid:
    label: 'Author ID'
    datasource_id: 'entity:node'
    property_path: uid
    type: integer
    indexed_locked: true
    type_locked: true
datasource_settings:
  'entity:group':
    bundles:
      default: false
      selected:
      - learning_path
    languages:
      default: true
      selected: {  }
  'entity:node':
    bundles:
      default: false
      selected:
      - article
      - forum
      - page
    languages:
      default: true
      selected: {  }
processor_settings:
  add_url:
    weights:
      preprocess_index: -30
  aggregated_field:
    weights:
      add_properties: 20
  content_access:
    weights:
      preprocess_index: -6
      preprocess_query: -4
  entity_status:
    weights:
      preprocess_index: -10
  highlight:
    highlight: always
    highlight_partial: true
    excerpt: true
    excerpt_length: 256
    exclude_fields:
    - field_learning_path_description
    - title
    prefix: '<strong>'
    suffix: '</strong>'
    weights:
      postprocess_query: 0
  html_filter:
    all_fields: false
    fields:
    - rendered_item
    - title
    title: true
    alt: true
    tags:
      b: 2
      h1: 5
      h2: 3
      h3: 2
      string: 2
    weights:
      preprocess_index: -3
      preprocess_query: -6
  ignorecase:
    all_fields: true
    fields:
    - author
    - field_learning_path_description
    - label
    - rendered_item
    - title
    - type
    weights:
      preprocess_index: -5
      preprocess_query: -8
  rendered_item:
    weights:
      add_properties: 0
      pre_index_save: -10
  stopwords:
    all_fields: false
    fields:
    - rendered_item
    - title
    stopwords:
    - a
    - an
    - and
    - are
    - as
    - at
    - be
    - but
    - by
    - for
    - if
    - in
    - into
    - is
    - it
    - 'no'
    - not
    - of
    - 'on'
    - or
    - s
    - such
    - t
    - that
    - the
    - their
    - then
    - there
    - these
    - they
    - this
    - to
    - was
    - will
    - with
    weights:
      preprocess_index: -5
      preprocess_query: -10
  tokenizer:
    all_fields: false
    fields:
    - rendered_item
    - title
    spaces: ''
    overlap_cjk: 1
    minimum_word_size: '3'
    weights:
      preprocess_index: -2
      preprocess_query: -5
  transliteration:
    all_fields: false
    fields:
    - rendered_item
    - title
    weights:
      preprocess_index: -4
      preprocess_query: -7
tracker_settings:
  default:
    indexing_order: fifo
options:
  index_directly: true
  cron_limit: 50
server: default_server
